/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StoriesStorySlugImport } from './routes/stories.$storySlug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesStorySlugRoute = StoriesStorySlugImport.update({
  id: '/stories/$storySlug',
  path: '/stories/$storySlug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/stories/$storySlug': {
      id: '/stories/$storySlug'
      path: '/stories/$storySlug'
      fullPath: '/stories/$storySlug'
      preLoaderRoute: typeof StoriesStorySlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stories/$storySlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stories/$storySlug'
  id: '__root__' | '/' | '/stories/$storySlug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesStorySlugRoute: typeof StoriesStorySlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesStorySlugRoute: StoriesStorySlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/stories/$storySlug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/stories/$storySlug": {
      "filePath": "stories.$storySlug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
